# Generated by Django 4.2 on 2023-04-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tevekenyseg',
            fields=[
                ('tevekenyseg_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tevekenyseg_nev', models.CharField(max_length=100, unique=True, verbose_name='Tevékenység neve')),
                ('pontszam', models.IntegerField(verbose_name='Pontszám')),
            ],
        ),
        migrations.CreateModel(
            name='Bejegyzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osztaly_id', models.CharField(choices=[('0', 'SZF1A'), ('1', 'SZF1B'), ('2', 'SZF2'), ('3', 'nSZF1A'), ('4', 'nSZF1B')], max_length=10, verbose_name='Osztály')),
                ('allapot', models.CharField(choices=[('Jóvahagyásra vár', 'Jóvahagyásra vár'), ('Jóváhagyott', 'Jóváhagyott')], default='', max_length=30, verbose_name='Állapot')),
                ('tevekenyseg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tevekenyseg', verbose_name='Tevékenység')),
            ],
        ),
    ]
